import './globals.css'
import type { Metadata } from 'next'
import { Dosis } from 'next/font/google'

import { ToasterProvider } from '@/providers/toast-provider';

const font = Dosis({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Aria Poker Tracker',
  description: 'Generated by bob with help from Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <ToasterProvider />
      <body className={font.className}>{children}</body>
    </html>
  )
}
